# Logistic Regression Algorithm Implemention

In [2]:
import numpy as np
import pandas as pd


In [14]:

df=pd.DataFrame({'age':[10,20,30,40,50],'bought_insurance':[1,1,1,1,0]})
df

age  bought_insurance
0   10                 1
1   20                 1
2   30                 1
3   40                 1
4   50                 0

In [17]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df[['age']],df.bought_insurance,train_size=0.9)


In [18]:
x_test

age
3   40

In [20]:
x_train

age
2   30
4   50
0   10
1   20

In [21]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [22]:
model.predict([[60]])

array([0], dtype=int64)

In [23]:
model.predict([[70]])

array([0], dtype=int64)

In [24]:
model.predict([[10]])

array([1], dtype=int64)

In [26]:
model.predict([[20]])

array([1], dtype=int64)